### ISSUE TITLE
Truncated comments in `lesson2.cfdg`?

### ISSUE THREAD

**Issue by follower** [MtnViewJohn/context-free#16]
These two sections of the second tutorial lesson seem to have the descriptive text truncated: 

https://github.com/MtnViewJohn/context-free/blob/97b4074601a6726abd52340f27aff16f9ad3fa05/input/lesson2.cfdg#L19-L24

https://github.com/MtnViewJohn/context-free/blob/97b4074601a6726abd52340f27aff16f9ad3fa05/input/lesson2.cfdg#L95-L100

Not sure if the "missing" text was never written in the first place or accidentally truncated when copied from somewhere else (couldn't find anything in the file history or via a quick Google search).

**Comment by MtnViewJohn** [comment]
Those comments have been truncated for a very long time. Probably they were never complete. I will complete these in the next release.

**Comment by MtnViewJohn** [comment]
Fixed in version 3.1
