### ISSUE TITLE
Recursive function causes SEGV while printing error

### ISSUE THREAD

**Issue by dkasak** [MtnViewJohn/context-free#20]
As the title says, something like

    r00()=r00

Causes a segfault by reading from an invalid address in
`CfdgError::CfdgError`.

Valgrind report:

    ==10116== Memcheck, a memory error detector
    ==10116== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
    ==10116== Using Valgrind-3.14.0.GIT and LibVEX; rerun with -h for copyright info
    ==10116== Command: cfdg-github 1
    ==10116== 
    ==10116== Invalid read of size 8
    ==10116==    at 0x13429C: CfdgError::CfdgError(yy::location const&, char const*) (cfdg.cpp:112)
    ==10116==    by 0x172B89: Builder::warning(yy::location const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (builder.cpp:151)
    ==10116==    by 0x172B40: Builder::error(yy::location const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (builder.cpp:145)
    ==10116==    by 0x134458: CfdgError::Error(yy::location const&, char const*, Builder*) (cfdg.cpp:150)
    ==10116==    by 0x1BE033: AST::ASTruleSpecifier::compile(AST::CompilePhase, Builder*) (astexpression.cpp:2630)
    ==10116==    by 0x1C713E: AST::Compile(std::unique_ptr<AST::ASTexpression, std::default_delete<AST::ASTexpression> >&, AST::CompilePhase, Builder*) (astexpression.h:485)
    ==10116==    by 0x1E9527: AST::ASTdefine::compile(AST::CompilePhase, Builder*) (astreplacement.cpp:897)
    ==10116==    by 0x1E4012: AST::ASTrepContainer::compile(AST::CompilePhase, Builder*, AST::ASTloop*, AST::ASTdefine*) (astreplacement.cpp:111)
    ==10116==    by 0x143FEA: CFDGImpl::rulesLoaded() (cfdgimpl.cpp:459)
    ==10116==    by 0x134EF1: CFDG::ParseFile(char const*, AbstractSystem*, int) (cfdg.cpp:279)
    ==10116==    by 0x21CDCA: main (main.cpp:454)
    ==10116==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
    ==10116== 
    ==10116== 
    ==10116== Process terminating with default action of signal 11 (SIGSEGV)
    ==10116==  Access not within mapped region at address 0x18
    ==10116==    at 0x13429C: CfdgError::CfdgError(yy::location const&, char const*) (cfdg.cpp:112)
    ==10116==    by 0x172B89: Builder::warning(yy::location const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (builder.cpp:151)
    ==10116==    by 0x172B40: Builder::error(yy::location const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (builder.cpp:145)
    ==10116==    by 0x134458: CfdgError::Error(yy::location const&, char const*, Builder*) (cfdg.cpp:150)
    ==10116==    by 0x1BE033: AST::ASTruleSpecifier::compile(AST::CompilePhase, Builder*) (astexpression.cpp:2630)
    ==10116==    by 0x1C713E: AST::Compile(std::unique_ptr<AST::ASTexpression, std::default_delete<AST::ASTexpression> >&, AST::CompilePhase, Builder*) (astexpression.h:485)
    ==10116==    by 0x1E9527: AST::ASTdefine::compile(AST::CompilePhase, Builder*) (astreplacement.cpp:897)
    ==10116==    by 0x1E4012: AST::ASTrepContainer::compile(AST::CompilePhase, Builder*, AST::ASTloop*, AST::ASTdefine*) (astreplacement.cpp:111)
    ==10116==    by 0x143FEA: CFDGImpl::rulesLoaded() (cfdgimpl.cpp:459)
    ==10116==    by 0x134EF1: CFDG::ParseFile(char const*, AbstractSystem*, int) (cfdg.cpp:279)
    ==10116==    by 0x21CDCA: main (main.cpp:454)
    ==10116==  If you believe this happened as a result of a stack
    ==10116==  overflow in your program's main thread (unlikely but
    ==10116==  possible), you can try to increase the size of the
    ==10116==  main thread stack using the --main-stacksize= flag.
    ==10116==  The main thread stack size used in this run was 8388608.
    ==10116== 
    ==10116== HEAP SUMMARY:
    ==10116==     in use at exit: 65,587 bytes in 235 blocks
    ==10116==   total heap usage: 585 allocs, 350 frees, 232,186 bytes allocated
    ==10116== 
    ==10116== LEAK SUMMARY:
    ==10116==    definitely lost: 0 bytes in 0 blocks
    ==10116==    indirectly lost: 0 bytes in 0 blocks
    ==10116==      possibly lost: 0 bytes in 0 blocks
    ==10116==    still reachable: 65,587 bytes in 235 blocks
    ==10116==         suppressed: 0 bytes in 0 blocks
    ==10116== Rerun with --leak-check=full to see details of leaked memory
    ==10116== 
    ==10116== For counts of detected and suppressed errors, rerun with: -v
    ==10116== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by MtnViewJohn** [comment]
Fixed in version 3.1
