### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by brianiac2point0** [MtnViewJohn/context-free#24]
Dead Link:
https://www.contextfreeart.org/mediawiki/index.php/CFDG_HOWTO

Windows version 3.0.11.3 v41 64 bit.
"Help"
"Writing CFDG Files..."

**Comment by MtnViewJohn** [comment]
Good catch! I have updated the server to redirect these links from the old wiki over to the new wiki on Github. Context Free 3.1 will have updated URLs in the help menu.

**Comment by brianiac2point0** [comment]
It's the least I can do.  I love the program and appreciate yours and everyone else's work that goes into it.  

    Le samedi 29 décembre 2018 à 02:51:56 UTC−5, John Horigan <notifications@github.com> a écrit :  
 
 
Good catch! I have updated the server to redirect these links from the old wiki over to the new wiki on Github. Context Free 3.1 will have updated URLs in the help menu.

**Comment by MtnViewJohn** [comment]
Fixed in version 3.1
