### ISSUE TITLE
Release dates at https://www.contextfreeart.org/downloads.html

### ISSUE THREAD

**Issue by rubyFeedback** [MtnViewJohn/context-free#26]
Hello John and others,

I think I discovered context-free in ... I don't quite remember. It was many years ago, though.

Since I have discovered it, I am looking back at it regularly, every some weeks or few months or so, give or take, especially at the gallery.

I also update the code every now and then, and in order to do this, I actually go to the "oldschool" page at:

https://www.contextfreeart.org/downloads.html

This leads me to the issue request here - would it be possible to also mention the release date at downloads.html? E. g. when a particular relase happened?

Right now at downloads.html it says that version 3.1 is the current release; I have 3.0.11.4 right now so I am considering updating. It would be a little help to indicate the release time so that I know how far behind I may be (I guess from 3.0.11.4 to 3.1 it may not be a huge change but it would still help a little if the release date would also be shown). At any rate please do feel free to close this issue at any moment in time - context-free is a really awesome idea, some of the autogenerated images are wonderful for wallpaper or small "art" icons to be used as random decorator on webpages too.

**Comment by MtnViewJohn** [comment]
If you scroll down the change log lists the release dates. For some reason I left out 3.0.11.4. I have fixed this. There aren't many changes on the Linux side from version 3.0.11.4 to version 3.1. There are some ill-formed cfdg files that crash 3.0.11.4 but produce an error message on 3.1. The main changes in 3.1 are for the Mac and Windows platforms.

**Comment by MtnViewJohn** [comment]
I have also added the release date to the top of the downloads page.
