### ISSUE TITLE
What are rule weights?

### ISSUE THREAD

**Issue by keller91711** [MtnViewJohn/context-free#28]
Rule weights are mentioned only once in the documentation but don't seem to be defined.

**Comment by MtnViewJohn** [comment]
They are described on the [Shape Rule page](https://github.com/MtnViewJohn/context-free/wiki/Shape-Rules#randomness-rule-weights-and-having-multiple-rules-for-a-shape).

**Comment by keller91711** [comment]
Since it is mentioned at the top level, shouldn't there be some kind of link or definition there?

**Comment by MtnViewJohn** [comment]
Good idea. I just added the link.

**Comment by MtnViewJohn** [comment]
Link added.
