### ISSUE TITLE
how could I count iterations?

### ISSUE THREAD

**Issue by cristianvogel** [MtnViewJohn/context-free#31]
Hi MtnViewJohn, thanks for the amazing context-free development. 

i was reading this part about Variables and trying to figure out how to count the iteration of a shape...  for example. But I'm not sure I am clear about how a global variable could be correctly implemented in this type of script?

```
startshape SEED1

CF::MinimumSize = 0.5



sine(t,amp,freq,phase) = amp*sin( freq*360*(t + phase) )
cosine(t,amp,freq,phase) = amp*cos( freq*260*(t+phase) )
iter = 0

shape SEED1 {
 //polygon6sided [ sat 0.6 hue 120 ]
 
 iter = iter + 1
 SQUARE [ sat 1 hue 120 b (iter*0.05) size (iter*2) 0.5 r (0...90) ]

 SEED1 [y 1.2 size 0.99 rotate 1.5]
 
 
 
}

shape SEED1 
 
  rule 0.05 {
  if (iter>5) flower ( 12 , 1 ) [s 4]
  SEED1 [flip ( 90+iter)]
  
}

shape SEED1 

  rule 0.05 {
 SEED1 [r -5 b -0.5 
                brightness 0.01]
 SEED1 [y 1. x -0.5 s 0.7 r 30 b -0.5 flip 90 
                brightness 0.1]
 SEED1 [y 1. x 0.5 s 0.7 r -30 b -0.5 flip 90
                brightness 0.05]
}


shape polygon6sided
{
	loop 3 [r 60] SQUARE [[rotate 0 size 0.866025 0.5]]
}

path flower(number petals, number filled) {
  MOVETO(cos(-180/petals), sin(-180/petals))
  loop petals [r (360/petals)]
    ARCTO(cos(180/petals), sin(180/petals), 
          0.4, 0.4 + 0.2 * (petals - 5), 90)
  CLOSEPOLY(CF::Align)
  if (filled) FILL[a -0.5]
  MOVETO(0.65, 0)
  ARCTO(-0.65, 0, 0.65, CF::ArcCW)
  ARCTO( 0.65, 0, 0.65, CF::ArcCW)
  CLOSEPOLY()
  FILL[a -0.5]
}```

**Comment by MtnViewJohn** [comment]
Context Free does not have mutable state. Variables are variables in the mathematical sense: they can have a variety of values. But once a Context Free variable is created its value cannot change. When you say `iter = iter + 1 ` you are declaring a local variable, also named **iter**, that is equal to the global variable**iter** + 1 (i.e. 1). Outside of this **SEED1** shape rule the **iter** global variable is in scope and has its fixed value of 0.

The best that you can do is give shape **SEED1** a natural parameter that gets incremented on each recursive call. Parent shapes can send info to their children shapes through parameters but siblings shapes can never talk to each other. This is the essence of context free grammars. If you do this then you will probably want to set **CF::MaxNatural** to some large value.
