### ISSUE TITLE
The download link for Mac on the website requires you to right click and select "save link as" 

### ISSUE THREAD

**Issue by Jay-Madden** [MtnViewJohn/context-free#33]
Clicking it does nothing otherwise 

MacOS: 10.15
Chrome Version: 87

**Comment by MtnViewJohn** [comment]
The web server was redirecting the link to the Amazon S3 URL where the files are actually located. But it was changing the protocol from https to http. Changing link security in a redirect is poor form and the latest versions of Chrome refuse to follow the redirect. I have updated the server to redirect using https and the link seems to work again. Thanks for the tip.
