### ISSUE TITLE
Issue installing on Ubuntu

### ISSUE THREAD

**Issue by paynejordand** [MtnViewJohn/context-free#34]
When downloading and attempting to run `make` or `sudo make install` on Ubunutu getting error
```
src-unix/posixSystem.cpp:37:10: fatal error: unicode/ucnv.h: No such file or directory
   37 | #include <unicode/ucnv.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:209: objs/posixSystem.o] Error 1
```
Ubuntu Version: 20.04.1
Gcc Version: 9.3.0
Flex Version: 2.6.4
Bison Version: 3.5.1
Libpng Version: 1.6.37

**Comment by MtnViewJohn** [comment]
I added a new dependency and forgot to document it. Add the package libicu-dev and try again.

**Comment by paynejordand** [comment]
That fixed it.
Thank you.
