### ISSUE TITLE
missing necessary library in readme to compile

### ISSUE THREAD

**Issue by retrue** [MtnViewJohn/context-free#35]
Hi
I followed the instructions in README, installed dependencies and when I typed 'make' it failed with this error:
#include "FlexLexer.h"
After checking the Internet, I found the solution. It is necessary to install **libfl-dev**.
I am using Linux Mint 20.1 (based on Ubuntu 20.04).

**Comment by MtnViewJohn** [comment]
Thanks for the tip. I have updated the README with the libfl-dev dependency.
