### ISSUE TITLE
Requirement: for XP but need .NET 4.5?

### ISSUE THREAD

**Issue by tumagonx** [MtnViewJohn/context-free#6]
I'm about to download 3.0.9 but confused by the requirement.
Homepage says it's for XP or later but NET 4.5 is only for Vista or later. Furthermore AFAIK the last VS able to target XP is VS2013.

Need clarification

**Comment by MtnViewJohn** [comment]
Support for Windows XP has now been dropped. I have just updated the download page to reflect that. Thanks for pointing out the mismatch.
